apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-frontend
  template:
    metadata:
      labels:
        app: myapp-frontend
    spec:
      containers:
      - name: myapp-frontend
        image: makeswarane/myapp-frontend:latest
        ports:
        - containerPort: 3000